server {
    listen 80;
    server_name sigtef.com.br www.sigtef.com.br;

    # Onde os arquivos do frontend ficarão
    root /var/www/sigtef/frontend/dist;
    index index.html;

    # Ocultar versão do nginx
    server_tokens off;

    # Headers de Segurança
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Bloquear arquivos ocultos
    location ~ /\. {
        deny all;
    }

    # Roteamento do Frontend (React/Vite Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para o Backend Spring Boot
    location /api/ {
        # Limitando payload size
        client_max_body_size 50M;
        
        proxy_pass http://127.0.0.1:8081/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Timeouts para evitar conexões presas
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
