package br.gov.go.seds.sigtef.model.enums;

public enum ImportType {
    LEGAL_ENTITIES,
    REPRESENTATIVES,
    PARTNERSHIP_AGREEMENTS,
    AGREEMENT_PROGRAMS,
    FINANCIAL_TRANSFERS,
    MONTHLY_EXECUTIONS,
    ACCOUNTABILITY_HISTORY,
    UTILITY_ACCOUNTS,
    BANK_ACCOUNTS,
    ENERGY_RECORDS
}
